# Generated by Django 2.2.4 on 2019-09-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='food_source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
