# Generated by Django 2.2.4 on 2019-09-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodproduct_food_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodproductnutrient',
            options={'ordering': ['-nutrient__rank']},
        ),
        migrations.AlterModelOptions(
            name='nutrient',
            options={'ordering': ['-rank']},
        ),
        migrations.AddField(
            model_name='nutrient',
            name='rank',
            field=models.IntegerField(default=-1, verbose_name='rank'),
        ),
    ]
