# Generated by Django 2.2.4 on 2019-09-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20190902_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodproduct',
            options={'ordering': ['full_name']},
        ),
    ]
