# Generated by Django 2.2.4 on 2019-09-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20190902_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='display_name',
            field=models.TextField(null=True, verbose_name='display name'),
        ),
    ]
