# Generated by Django 2.2.4 on 2019-09-10 11:24
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20190910_0754'),
    ]

    operations = [
        BtreeGinExtension(),
    ]
