# Generated by Django 2.2.4 on 2019-09-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20190910_1124'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foodproduct',
            index=models.Index(fields=['food_source'], name='food_foodpr_food_so_597549_idx'),
        ),
    ]
