# Generated by Django 2.2.4 on 2019-09-15 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20190910_1128'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodproductunit',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='FoodProductSearchCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Food product')),
                ('food_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.FoodProduct', verbose_name='Food product')),
            ],
        ),
    ]
