# Generated by Django 2.2.4 on 2019-09-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20190915_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproductunit',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Portion description'),
        ),
        migrations.AddField(
            model_name='foodproductunit',
            name='modifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Portion modifier'),
        ),
    ]
