# Generated by Django 2.2.4 on 2019-09-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20190915_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproductsearchcacheitem',
            name='text',
            field=models.CharField(max_length=255, unique=True, verbose_name='Food product'),
        ),
        migrations.AddIndex(
            model_name='foodproductsearchcacheitem',
            index=models.Index(fields=['text'], name='food_foodpr_text_1a40df_idx'),
        ),
    ]
