# Generated by Django 2.2.4 on 2020-05-31 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_auto_20190915_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProductSynonyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True, verbose_name='Food product')),
                ('food_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='food.FoodProduct', verbose_name='Food product')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodProductSearchCacheItem',
        ),
        migrations.AddIndex(
            model_name='foodproductsynonyms',
            index=models.Index(fields=['text'], name='food_foodpr_text_d170aa_idx'),
        ),
    ]
