# Generated by Django 2.2.4 on 2020-05-31 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_auto_20200531_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproductsynonym',
            name='food_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_name', to='food.FoodProduct', verbose_name='Food product'),
        ),
    ]
