# Generated by Django 2.2.4 on 2020-05-31 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_auto_20200531_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproductsynonym',
            name='food_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='food.FoodProduct', verbose_name='Food product'),
        ),
        migrations.AlterField(
            model_name='foodproductsynonym',
            name='text',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
    ]
