# Generated by Django 2.2.4 on 2020-06-01 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_auto_20200531_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProductCommonNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('text_plural', models.CharField(blank=True, max_length=255, null=True, verbose_name='name plural')),
                ('food_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_names', to='food.FoodProduct', verbose_name='Food product')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodProductSynonym',
        ),
        migrations.AddIndex(
            model_name='foodproductcommonnames',
            index=models.Index(fields=['text'], name='food_foodpr_text_234304_idx'),
        ),
    ]
