# Generated by Django 2.2.4 on 2020-06-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_auto_20200601_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodProductCommonNames',
            new_name='FoodProductCommonName',
        ),
        migrations.RemoveIndex(
            model_name='foodproductcommonname',
            name='food_foodpr_text_234304_idx',
        ),
        migrations.AddIndex(
            model_name='foodproductcommonname',
            index=models.Index(fields=['text'], name='food_foodpr_text_15418f_idx'),
        ),
    ]
