# Generated by Django 2.2.4 on 2020-06-08 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_auto_20200601_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='grams_per_ml',
            field=models.FloatField(default=0, help_text='Number of grams in a ml of this product. E.g. a ml of milk is 1.035 gr.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Grams in a ml'),
        ),
        migrations.AddField(
            model_name='foodproductunit',
            name='quantity',
            field=models.IntegerField(default=1, help_text='The default quantity of this portion.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='is_constant',
            field=models.BooleanField(choices=[(True, 'unit'), (False, 'portion')], default=True, help_text='Determines whether a unit is constant. \n                                                    100 ml is the same for every product, 1 portion is not.', verbose_name='type'),
        ),
    ]
