# Generated by Django 2.2.4 on 2019-09-10 08:28

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='unique identifier')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('user_date', models.DateField(verbose_name='user date')),
                ('user_time', models.TimeField(verbose_name='user time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'voice session',
                'ordering': ['uuid'],
            },
        ),
        migrations.CreateModel(
            name='VoiceSessionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('user_created', models.BooleanField(default=True, verbose_name='chat item was created by user')),
                ('type', models.CharField(choices=[('user_input', 'User input.'), ('feedback', 'Voice assistant feedback.'), ('clarification_question', 'Voice assistant clarification question.'), ('objects_created', 'Object created')], max_length=255, verbose_name='type of chat item')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text of the chat item')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='additional data')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='voice.VoiceSession', verbose_name='voice session')),
            ],
            options={
                'verbose_name': 'voice session item',
                'ordering': ['created_on'],
            },
        ),
    ]
