# Generated by Django 2.2.4 on 2019-09-10 10:48
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
