# Generated by Django 2.2.4 on 2019-09-15 21:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_auto_20190910_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSessionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=255, unique=True, verbose_name='code')),
                ('responses', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
            ],
            options={
                'verbose_name': 'voice session response',
            },
        ),
    ]
