# Generated by Django 2.2.4 on 2019-09-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['created_on'], 'verbose_name': 'diary entry', 'verbose_name_plural': 'diary entries'},
        ),
    ]
