# Generated by Django 2.2.4 on 2019-09-05 13:52

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20190904_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='entry Date'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='entry Time'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.Unit', verbose_name='unit'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
