# Generated by Django 2.2.4 on 2019-09-08 14:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20190905_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.Unit', verbose_name='unit'),
        ),
    ]
