# Generated by Django 2.2.4 on 2019-09-09 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20190908_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-date', 'time'], 'verbose_name': 'diary entry', 'verbose_name_plural': 'diary entries'},
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity'),
        ),
    ]
