# Generated by Django 2.2.4 on 2020-06-08 22:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_auto_20200608_1538'),
        ('diary', '0007_auto_20200512_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='portion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.FoodProductUnit', verbose_name='portion'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(blank=True, help_text='A custom title for this diary entry.', max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='entry date'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='entry time'),
        ),
    ]
